'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
)

function DrawerCard({ emoji, title, subtitle, href, color = 'orange' }) {
  const colors = {
    orange: 'bg-orange-100 text-orange-900',
    green: 'bg-green-100 text-green-900',
    blue: 'bg-blue-100 text-blue-900',
    purple: 'bg-purple-100 text-purple-900',
    amber: 'bg-amber-100 text-amber-900',
    teal: 'bg-teal-100 text-teal-900',
  }
  return (
    <button onClick={() => window.location.href = href}
      className="w-full text-left border border-gray-200 rounded-2xl overflow-hidden hover:border-orange-200 hover:shadow-sm transition-all">
      <div className={`px-4 py-3 font-bold text-sm ${colors[color]}`}>
        {emoji} {title}
      </div>
      {subtitle && (
        <div className="px-4 py-3 text-sm text-gray-500">{subtitle}</div>
      )}
    </button>
  )
}

export default function KitchenPage() {
  const [user, setUser] = useState(null)

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (!session) { window.location.href = '/login'; return }
      setUser(session.user)
    })
  }, [])

  return (
    <div className="min-h-screen bg-white">
      <header className="bg-white border-b border-gray-100 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <h1 className="text-2xl font-bold text-gray-900">🍳 My Kitchen</h1>
          <p className="text-sm text-gray-400 mt-0.5">Your recipe hub</p>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-6 space-y-3">
        <DrawerCard emoji="🔒" title="MyRecipes" subtitle="Your personal recipe collection with photos and notes" href="/secret" color="orange" />
        <DrawerCard emoji="🎴" title="MyRecipe Deck" subtitle="Swipe through recipes for inspiration" href="/explore" color="amber" />
        <DrawerCard emoji="🔍" title="Browse Recipes" subtitle="Search our full recipe library" href="/recipes" color="orange" />
        <DrawerCard emoji="❤️" title="Your Favorite Recipes" subtitle="Recipes you've saved and loved" href="/saved" color="orange" />
        <DrawerCard emoji="🃏" title="My Recipe Cards" subtitle="Quick reference cards for your go-to recipes" href="/cards" color="amber" />
        <DrawerCard emoji="🎬" title="Cooking Videos" subtitle="379 videos from top YouTube cooking channels" href="/videos" color="orange" />
        <DrawerCard emoji="🎓" title="Chef Education" subtitle="Recipe-first channels — always includes ingredients & instructions" href="/education" color="green" />
        <DrawerCard emoji="👨‍🍳" title="AI Chef Creations" subtitle="Gourmet recipes generated by AI" href="/topchef" color="purple" />
        <DrawerCard emoji="📅" title="Meal Planner" subtitle="Plan your meals for the week" href="/weeklyplan" color="teal" />
        <DrawerCard emoji="🤖" title="MyChef AI" subtitle="Ask your personal AI chef anything" href="/chef" color="orange" />
      </main>
    </div>
  )
}