export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="bg-white border-b border-gray-100 sticky top-0 z-10">
        <div className="max-w-2xl mx-auto px-4 py-3 flex items-center gap-2">
          <a href="/" className="text-sm text-gray-500 hover:text-gray-600">← Back</a>
          <h1 className="text-lg font-bold text-gray-900">Terms of Service</h1>
        </div>
      </header>
      <main className="max-w-2xl mx-auto px-4 py-8 space-y-6 text-gray-700">
        <p className="text-sm text-gray-500">Last updated: May 2026</p>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">1. Acceptance of Terms</h2>
          <p className="text-sm leading-relaxed">By using MyRecipe Companion ("the App"), you agree to these Terms of Service. If you do not agree, do not use the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">2. Your Account</h2>
          <p className="text-sm leading-relaxed">You are responsible for maintaining the security of your account. You must provide accurate information when creating your account. We reserve the right to terminate accounts that violate these terms.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">3. Your Content</h2>
          <p className="text-sm leading-relaxed">Recipes, notes, photos, and other content you save in your vault ("Your Content") remain yours. By using the App, you grant My Companion Apps a limited license to store and display Your Content solely to provide the service to you.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">4. AI-Generated Recipes</h2>
          <p className="text-sm leading-relaxed">Recipes generated by Chef Jen AI are created for your personal use. You may share these recipes for personal, non-commercial purposes. You may not sell, license, or commercially exploit AI-generated recipes without our written permission. When sharing recipes on social media, you may not attach advertisements or monetize those posts in any way that implies commercial endorsement by My Companion Apps.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">5. Acceptable Use</h2>
          <ul className="text-sm leading-relaxed space-y-2 list-disc pl-4">
            <li>You may not use the App for any unlawful purpose</li>
            <li>You may not attempt to reverse engineer or copy the App</li>
            <li>You may not use the App to scrape or harvest data</li>
            <li>You may not share your account credentials with others</li>
            <li>You may not commercially monetize content shared from the App without written permission</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">6. Subscription and Billing</h2>
          <p className="text-sm leading-relaxed">Some features require a paid subscription. Subscriptions auto-renew unless cancelled. You can manage or cancel your subscription at any time through your account settings or the App Store. Refunds are handled per Apple App Store or Google Play Store policies.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">7. Disclaimer of Warranties</h2>
          <p className="text-sm leading-relaxed">The App is provided "as is" without warranties of any kind. AI-generated recipes and cooking advice are for informational purposes only. Always use your own judgment when preparing food. We are not responsible for any adverse outcomes from following recipes in the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">8. Limitation of Liability</h2>
          <p className="text-sm leading-relaxed">My Companion Apps shall not be liable for any indirect, incidental, or consequential damages arising from your use of the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">9. Changes to Terms</h2>
          <p className="text-sm leading-relaxed">We may update these terms at any time. Continued use of the App after changes constitutes acceptance of the new terms.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-2">10. Contact</h2>
          <p className="text-sm leading-relaxed">Questions about these terms? Contact us at <a href="mailto:support@mycompanionapps.com" className="text-orange-600 underline">support@mycompanionapps.com</a></p>
        </section>
      </main>
    </div>
  )
}